### ISSUE TITLE
Cosmos DB state store not setting partitionKey on state transactions

### ISSUE THREAD

**Issue by JonathanLydall** [dapr/components-contrib#2880]
## Expected Behavior

When using a transaction to upsert to a Cosmos DB state store, the `partitionKey` field should not be blank.

## Actual Behavior

An example of the document once saved:

```json
{
    "id": "orderprocessing||order_1",
    "value": "250",
    "isBinary": false,
    "partitionKey": "",
    "Etag": "",
    "_rid": "zXQ1AO0LbbEBAAAAAAAAAA==",
    "_self": "dbs/zXQ1AA==/colls/zXQ1AO0LbbE=/docs/zXQ1AO0LbbEBAAAAAAAAAA==/",
    "_etag": "\"0300cc6a-0000-3000-0000-64789c4d0000\"",
    "_attachments": "attachments/",
    "_ts": 1685625933
}
```

## Steps to Reproduce the Problem

I first noticed the problem when trying with the .NET SDK, but it's easily reproduceable with PowerShell.

Change your state store component configuration to the following (which is configured for the Cosmos DB emulator, but the same issue occurs with a regular Azure Cosmos DB instance):

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: https://localhost:8081
  - name: masterKey
    value: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw== # local
  - name: database
    value: DaprDatabase
  - name: collection
    value: DaprContainer
```

Start a Dapr side car:

```powershell
dapr --app-id orderprocessing --dapr-http-port 3601 run
```

Run the following:

```powershell
Invoke-RestMethod -Method Post -ContentType 'application/json' -Body '{"operations": [{"operation":"upsert", "request": {"key": "order_1", "value": "250"}}, {"operation":"upsert", "request": {"key": "order_2", "value": "250"}}]}' -Uri 'http://localhost:3601/v1.0/state/statestore/transaction'
```

I've also tried the following (I would actually expect the above to fail with the partition keys being different):

```powershell
Invoke-RestMethod -Method Post -ContentType 'application/json' -Body '{"operations": [{"operation":"upsert", "request": {"key": "order_1", "value": "250"}, "metadata": {"partitionKey": "orderGroup1"}}, {"operation":"upsert", "request": {"key": "order_2", "value": "250"}, "metadata": {"partitionKey": "orderGroup1"}}]}' -Uri 'http://localhost:3601/v1.0/state/statestore/transaction'
```

## Release Note

RELEASE NOTE: **FIX** Bug in runtime.

**Comment by ItalyPaleAle** [comment]
Thanks for reporting this! This is already being fixed in Dapr 1.11.0

**Comment by kamleshsen** [comment]
I am facing this exact issue in Dapr 1.14.4

**Comment by amolenk** [comment]
Just ran into the same issue (also on 1.14.4) while trying to use the outbox.

**Comment by kamleshsen** [comment]
@amolenk - I was able to proceed here. By sending partitionkey as query string parameter for transaction api.

**Comment by amolenk** [comment]
I tried a smaller example and that does work. Both when sending partitionKey as a query string parameter and sending the metadata as part of the request body:

```json
POST http://localhost:3500/v1.0/state/statestore/transaction?metadata.partitionKey=foo

{
  "operations": [
    {
      "operation": "upsert",
      "request": {
        "key": "order1",
        "value": {
            "orderId": "7hf8374s",
            "type": "book",
            "name": "assasin's apprentice"
        }
    }
    }
  ]
}
```

```json
POST http://localhost:3500/v1.0/state/statestore/transaction

{
  "operations": [
    {
      "operation": "upsert",
      "request": {
        "key": "order2",
        "value": {
            "orderId": "7hf8374s",
            "type": "book",
            "name": "assasin's apprentice"
        }
      }
    }
  ],
  "metadata": {
    "partitionKey": "foo"
  }
}
```

I'm still not having any luck trying to set the partitionKey when using the .NET SDK, but I'll do some more testing on that.

**Comment by kamleshsen** [comment]
@amolenk - Did you able to make this work. I am stuck with CosmosDB as statestore and Redis as my Pubsub. My message is getting saved in Cosmos but not getting delivered to outbox pubsub internal topic.

**Comment by Dudssource** [comment]
Hi folks, to everyone who gets stuck with this problem.

It lies on a limitation from cosmos db itself, where transactional requests requires every item on the  batch to share the same partition key ([docs](https://learn.microsoft.com/en-us/rest/api/cosmos-db/transactional-batch)).

I believe this behaviour should be documented on Dapr docs, since Dapr cosmosdb transactional implementation [uses the partitionKey metadata](https://github.com/dapr/components-contrib/blob/main/state/azure/cosmosdb/cosmosdb.go#L506) instead of key (as there'd be conflicts).
