### ISSUE TITLE
telemetry forwarded to Application Insights is incomplete

### ISSUE THREAD

**Issue by KaiWalter** [dapr/components-contrib#338]
## Expected Behavior

When using the native trace exporter and the Application Insights forwarder I would expect, that all requests, traces and dependencies telemetry is rendered to Application Insights.

## Actual Behavior

For a sample case - actor is instantiated by a service invocation (or messagebus binding), pub/subs 2 others services and is updated by these - only this is recorded in Application Insights:

| type | count | content |
| ---- | ---- | ---- |
| traces | 1 | AI: Local storage access has resulted in an error (User: ) (CustomFolder: ). If you want Application Insights SDK to store telemetry locally on disk in case of transient network issues please give the process access to %LOCALAPPDATA% or %TEMP% folder. If application is running in non-windows platform, create StorageFolder yourself, and set ServerTelemetryChannel.StorageFolder to the custom folder name. After you gave access to the folder you need to restart the process. Currently monitoring will continue but if telemetry cannot be sent it will be dropped |
| customEvents | 2 | /opencensus.proto.agent.trace.v1.TraceService/Export.node<br/>/opencensus.proto.agent.trace.v1.TraceService/Config.node |
| dependencies | 2 | target/name: PublishEvent: xxxx |

Forwarder is picking up batches with this message:

```
2020/05/16 05:59:21.823|INFO|OpenCensus input: [ConnectionCount: 0, BatchesReceiv
ed: 1, BatchesFailed: 0, ConfigsReceived: 2, ConfigsFailed: 0]
```

## Steps to Reproduce the Problem

followed [these instructions](https://github.com/dapr/docs/blob/master/howto/diagnose-with-tracing/azure-monitor.md)

### started forwarer locally

```
docker run -e APPINSIGHTS_INSTRUMENTATIONKEY={instrumentationKey} -e APPINSIGHTS_LIVEMETRICSSTREAMAUTHENTICATIONAPIKEY={apiKey} -d -p 55678:55678 daprio/dapr-localforwarder:latest
```

### added component native.yaml

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: native
  namespace: default
spec:
  type: exporters.native
  metadata:
  - name: enabled
    value: "true"
  - name: agentEndpoint
    value: "localhost:55678"
```

### created tracing.yaml

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: "1"
```

### referenced tracing.yaml when starting Daprd

```
daprd --app-id "magic-app" `
    --app-port "5000" `
    --placement-address 50005 `
    --log-level debug `
    --components-path ./components/ `
    --config ./tracing.yaml `
    --dapr-http-port 3500 `
    --dapr-grpc-port 50001
```

## dapr --version

CLI version: 0.7.0
Runtime version: 0.7.0

**Comment by yaron2** [comment]
cc @youngbupark @shalabhms

**Comment by shalabhms** [comment]
@KaiWalter , we have released Runtime version: 0.7.1 to address some fixes. 
Could  you please try 0.7.1 and update the result ?

**Comment by KaiWalter** [comment]
@shalabhms sorry, is https://github.com/dapr/cli/releases the right place to look for 0.7.1? Or would I need it to build myself?

**Comment by yaron2** [comment]
For running locally, you can use:

dapr init --runtime-version 0.7.1

**Comment by KaiWalter** [comment]
Thanks @yaron2 @shalabhms - after reinstalling CLI, runtime was upgraded to 0.7.1; next time I'll use the more elegant parameter you provided.

OK, with 0.7.1 there is a slight improvement: now I get pub/sub `dependencies`like `PublishEvent: ComplianceCheck` and `requests` for the pub/sub like `DeliveredEvent: ComplianceCheck`.

I am still missing - maybe this will be supported later :

1. telemetry for the initial service invocation like

```powershell
Invoke-RestMethod -Method POST -Uri "http://localhost:3500/v1.0/invoke/myapp/method/OrderEntry" -Body '{"OrderId":"42"}' -ContentType application/json
```

when invoking the very same method from a ServiceBus binding, a `requests` with `Binding: order-processing-inbound`is logged.


2. telemetry for the actor invocations

```C#
            var actorId = new ActorId(orderMessage.ActorId);
            var proxy = ActorProxy.Create<IOrderProcessingActor>(actorId, nameof(OrderProcessingActor));
            await proxy.ReportStatus(orderMessage, true);
```

3. some basic payload logged in `requests` to be able to relate telemetry

**Comment by shalabhms** [comment]
@KaiWalter , I have a question about point 1. Is the scenario working earlier in 0.6.0 and found to regressed ?  You should see telemetry for service invocation .

We have tracking issue https://github.com/dapr/dapr/issues/1513 in 0.8.0 for user app to get trace id from Dapr side car.

**Comment by KaiWalter** [comment]
@shalabhms I downgraded runtime and .NET SDK to `0.6.0` but with that configuration I do not even get the `dependencies` I originally reported.

Reverting back to `0.7.1` gave me back the behaviour I stated earlier immediately.

**Comment by shalabhms** [comment]
Thanks @KaiWalter for confirmation. Yes, in 0.7.1 tracing is improved . There is one issue dapr/dapr#1513 that we target in 0.8.0. If you find gaps, please raise the issue and we will address the in upcoming milestone.

**Comment by amanbha** [comment]
@KaiWalter Is this still an issue with 0.8.0
