### ISSUE TITLE
RabbitMQ pubsub - Kubernetes - Incorrect queue to exchange bindings when multiple topics are defined and replicas > 1 causing incorrect message delivery.

### ISSUE THREAD

**Issue by slacksach** [dapr/components-contrib#826]
## Expected Behavior
When running a Dapr app with multiple instances the RabbitMQ pubsub component should correctly add an Exchange for **Topic A** and a Queue for **Topic A** with a binding to Exchange **Topic A**

## Actual Behavior
When scaling the number of replicas either manually or automatically using a HPA we have observed that Topic Queues are bound to multiple incorrect Exchanges resulting in incorrect message routing.

The issue is easily replicated by scaling to a high number of replicas. Eg: 9

**In other words:** Topic A queue has bindings for Topic A and Topic B exchange
![image](https://user-images.githubusercontent.com/75119677/115238787-fe6eee00-a115-11eb-8cbf-2b167f9767c1.png)

## Steps to Reproduce the Problem

**Pre-requisites**
- Kubernetes Cluster (_Have replicated issue using AKS 1.19.3 and 1.20.5 and using minikube 1.19.0 with k8s 1.20.2_)
- RabbitMQ (_Confirmed issue on 3.8.8 and 3.8.14_)
- Dapr v1.0.1

**To Reproduce**
- Create a pubsub component using your RabbitMQ server
- Create a new Dapr application and subscribe it to 2 or more topics.
- Deploy the application to kubernetes and set replicas to 1
- View the RabbitMQ Management UI and observe that the Queue > Exchange binding is 1:1
- Now update the deployment and set replicas to 6
- View the RabbitMQ Management UI and observe that some (not all) queues now have multiple exchange bindings to the wrong exchanges for the queue.

## Release Note
RELEASE NOTE: Fix incorrect queue to exchange binding

**Comment by slacksach** [comment]
Anyone able to look into this one as at the moment it means that the RabbitMQ pubsub fails when replicas are greater than 1.

**Comment by slacksach** [comment]
bump..

**Comment by slacksach** [comment]
@yaron2 @pkedy still an issue, can we mark as good first issue/help wanted.

**Comment by slacksach** [comment]
@yaron2 @pkedy can we re-open, this is still an issue, can we mark as good first issue/help wanted.

**Comment by pkedy** [comment]
Absolutely 😀

**Comment by yaron2** [comment]
Assigned to 1.4

**Comment by yaron2** [comment]
@pkedy @berndverst do you have bandwidth to look into this? I spoke to @slacksach this morning and this is a real issue for production.

**Comment by dmitsh** [comment]
hey @slacksach ,

I've been trying to reproduce this issue, but with little success.
In fairness, I didn't use same versions as your's. But if we have a bug in Dapr, that shouldn't really matter.

I stood up an AKS cluster running k8s v1.21.2, and deployed Rabbitmq cluster v3.8.21.
In my test scenario I have a publisher that writes to 2 topics, and a subscriber that reads from them. I scaled the subscriber to 9 pods and run the test overnight.

I also deployed Prometheus server to count all instances where subscriber got data from unexpected topic.

When I checked, over 30K messages have been pushed to both topics, and none were received by mistake.
I also checked and verified correctness of bindings in RabbitMQ management UI.

I pushed my code and configuration to GitHub. Please take a look:
https://github.com/dmitsh/dapr-demo/tree/main/cmd/pubsub
https://github.com/dmitsh/dapr-demo/tree/main/deployments/pubsub
https://github.com/dmitsh/dapr-demo/blob/main/scripts/deploy-rabbitmq.sh

Let me know if I should try any modifications to reproduce the issue.

**Comment by slacksach** [comment]
Hi @dmitsh,

Thanks for this and for publishing your code/config. I'll have a run through tomorrow to see if I can find out where my setup is different

**Comment by dmitsh** [comment]
@slacksach,  I repeated the test with Dapr v1.0.1 (as opposed to the latest v1.4.2), but still could not reproduce the issue.
Will wait for your comments.

**Comment by slacksach** [comment]
@dmitsh was able to Repro it on our Dapr v1.3.2 environment
NET 5.0
Dapr v1.3.2

I scaled replicas to 10 from 1 in an app that is both a Publisher and a Subscriber, here's the screenshot showing the incorrectly bound events:
![image](https://user-images.githubusercontent.com/75119677/135649110-c66c28a8-d466-40a2-bbad-2a75ea976982.png)

Actions annotated as follows using the Dapr.AspNetCore library
`[Topic(PubSubConstants.PubSubName, TopicConstants.ErrorOccurred)]`

**pubsub.yaml**
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      secretKeyRef:
        name: rmq
        key: connectionstring
    - name: durable
      value: true
    - name: requeueInFailure
      value: true
```

**Comment by dmitsh** [comment]
Thanks @slacksach, any chance you can run my bits in your env?

**Comment by slacksach** [comment]
@dmitsh sure thing, I'll probably get to that this evening, sorry for the delay, hectic times hehe

I did notice in the logs the following showing the behaviour happening:
```
rabbitmq pub/sub: binding queue 'companies-api-manual-intervention-required' to exchange 'business-loan-provider-decision-received'
rabbitmq pub/sub: error in subscription for companies-api-check-with-providers-acknowledgement, Exception (503) Reason: "unexpected command received"
```

**Comment by dmitsh** [comment]
@slacksach , one difference between your and mine cases is that you scale up both publishers and subscribers, while I only scale up the subscribers. Let me do the same and re-run it.

**Comment by slacksach** [comment]
> @slacksach , one difference between your and mine cases is that you scale up both publishers and subscribers, while I only scale up the subscribers. Let me do the same and re-run it.

That's a good point, in our case our API is both a Publisher and a Subscriber within the same application.

I noticed that it is possible to exacerbate the situation by scaling up then down back up again and so on, the list of rogue bindings climbs each time.

**Comment by slacksach** [comment]
> @slacksach , one difference between your and mine cases is that you scale up both publishers and subscribers, while I only scale up the subscribers. Let me do the same and re-run it.

That's a good point, in our case our API is both a Publisher and a Subscriber within the same application.

I noticed that it is possible to exacerbate the situation by scaling up then down back up again and so on, the list of rogue bindings climbs each time and does not appear to be predictable.

**Comment by slacksach** [comment]
One other thing we noticed was that setting:
    - name: durable
      value: "false"

in the component the RabbitMQ Queue is still creating as a durable
![image](https://user-images.githubusercontent.com/75119677/135658837-c168e204-e9ca-4c4f-8044-123c56017d2a.png)

**Comment by dmitsh** [comment]
> One other unrelated thing we noticed was that setting durable in the RabbitMQ component was not taken into account on the server

I noticed that as well, will investigate

**Comment by dmitsh** [comment]
I've added another executable for combined pub/sub (https://github.com/dmitsh/dapr-demo/blob/main/cmd/pubsub/pubsub/main.go) and deployed it in my cluster (https://github.com/dmitsh/dapr-demo/blob/main/deployments/pubsub/pubsub.yml)
So far so good, but I will keep monitoring.
Please try it in your env.

Regarding 'durable', I sent a PR https://github.com/dapr/components-contrib/pull/1183, which was already merged.

**Comment by dmitsh** [comment]
@slacksach , another question. How quick does this issue occur in your setup?

**Comment by slacksach** [comment]
Hi @dmitsh, issue occurs immediately, as soon as the deployment is scaled to multiple instances.

**Comment by slacksach** [comment]
Hi @dmitsh, issue occurs immediately without requiring any messages to be published, as soon as the deployment is scaled to multiple instances.

**Comment by slacksach** [comment]
@dmitsh, good news, well hopefully. I've managed to reproduce this one entirely locally and put together a sample .NET Core Project and associated deployment manifests/pubsub component etc..
https://github.com/slacksach/daprpublisherrepro
Apologies that I've not yet run it using the code you provided but hopefully the repro helps.

**Comment by dmitsh** [comment]
@slacksach , thank you for setting up the repo. I was able to reproduce the issue.
I also noticed multiple AMQP errors 503 (unexpected command received).
I did a quick test and updated rabbitmq version from 3.8.9 to 3.9.7.
After that I could not reproduce the errors.
It seems that this problem has been addressed in one of the latest rabbitmq releases.

Could you give it a try?

**Comment by dmitsh** [comment]
@slacksach , I need to take it back :)
I was able to reproduce it in my setup with 3.9.7.
It happens less frequent compared to with 3.8.9, but still happens.
I keep digging ...

**Comment by slacksach** [comment]
Thanks @dmitsh, saw your reply just before I was about to push upgrade on my instances hehe :), if there's anything I can do to assist please let me know.

**Comment by dmitsh** [comment]
@slacksach , I keep working on this issue. So far I pushed a PR that addresses an issue of open channels (#1190).
This seems to improve stability and significantly reduce frequency of the issue occurrences.
However, I still see occasional errors reported by RabbitMQ server: `operation basic.consume caused a connection exception not_allowed: "attempt to reuse consumer tag '<queue name>'"` and wrong binding in the management UI.
Having said that, I was constantly monitoring the subscribers and I confirmed that none of them got the wrong message ever.

I have a few questions/requests for you. 
1. Do you have any insights about the nature of `attempt to reuse consumer tag` errors?
2. How did you deploy your RabbitMQ cluster? I.e., did you use rabbitmq operator, bitnami help chart, or some other way?
3. Could you use the current master branch of components-contrib and try and reproduce the problem? If you do, could you check the subscribers for unexpected messages? Let me know if you need any assistance with that. We can set up an online troubleshooting session if needed.

**Comment by dmitsh** [comment]
@slacksach , I'm somehow convinced that the problem is *not* in Dapr.
I triple-checked every call to `amqp.Channel.QueueBind` for correctness of parameters. The problem happens when this call returns error `unexpected command received`. After that the UI shows incorrect binding.
I created issue https://github.com/streadway/amqp/issues/516 and will follow up on it.

**Comment by slacksach** [comment]
Thanks @dmitsh, I would agree, definitely seems to be an issue in the underlying package. If you need any further info from my side please let me know.

**Comment by trondhindenes** [comment]
We're seeing this as well - it only started happening for us when apps started subscribing to more than 2 topis (I believe)

**Comment by dmitsh** [comment]
We fixed several issues in RabbitMQ (https://github.com/dapr/components-contrib/pull/1278).
These changes will be available in the v1.5.1 release.
@slacksach , @trondhindenes , could you try the RC https://github.com/dapr/dapr/releases/tag/v1.5.1-rc.2 ?

**Comment by trondhindenes** [comment]
@dmitsh Nice! I'm afraid we just moved to a one-topic-per-pubsub model, we couldn't live with the issues even in nonprod. So I'm afraid I'm not able to test the rc.

**Comment by dmitsh** [comment]
@slacksach , @trondhindenes , we have released v1.5.1, which contains the fix for RabbitMQ race condition.
https://github.com/dapr/dapr/releases/tag/v1.5.1
Please give it a try and let us know.

**Comment by slacksach** [comment]
Thanks @dmitsh, I'll retry with my repro, will likely be Wednesday before I get a chance to properly test

**Comment by slacksach** [comment]
@dmitsh @yaron2 - Looks good, tested with 15 replicas using my Repro and all SUCCESS, awesome work guys thank you! - Happy for you to close as fixed in v1.5.1

**Comment by slacksach** [comment]
@dmitsh @yaron2 unfortunately although the rogue messages issue doesn't exist we still see this which causes the PODs to terminate, sometimes they start, sometimes not :(
{appid}-{topicName}: Exception (503) Reason: \"unexpected command received\""

**Comment by dmitsh** [comment]
@slacksach , what is the way to reproduce this?

**Comment by slacksach** [comment]
Hi @dmitsh, I'm unable to reproduce it on my local repro repository. At the moment it only occurs in our Azure environments, I'll keep investigating to see if I can get it to fail locally with the same errors.

**Comment by dmitsh** [comment]
I can try and reproduce it in Azure, if you could provide instructions

**Comment by dmitsh** [comment]
And just to clarify, do you still see incorrect binding in Azure?

**Comment by WhoAteDaCake** [comment]
I've attempted to use 1.5.1 within AKS and also am getting channel not initialised error, even if channel exists https://github.com/dapr/components-contrib/issues/1371

**Comment by slacksach** [comment]
@dmitsh the incorrect binding issue seems to have gone away in my local testing which is great. I'll do another Azure test later today to confirm, I'll use the latest image you mentioned in #1371

**Comment by slacksach** [comment]
Closing as the duplicate bindings issue appears resolved, have confirmed with local tests. Thanks @dmitsh @yaron2
